In [82]:
import requests
import json
import pandas as pd

## WNBA shot tracking data

#### 2004 - 2014 Regular Season

In [83]:
url_base = 'https://stats.wnba.com/stats/shotchartdetail'

# DT did not play for 2015 season so have to scrape in chunks and merge later.
df = pd.DataFrame()

for x in range(2004, 2015):
        
    headers = {
        'Host': 'stats.wnba.com',
        'Connection': 'keep-alive',
        'Accept': 'application/json, text/plain, */*',
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36',
        'Referer': 'https://stats.wnba.com/',
        "x-wnba-stats-origin": "stats",
        "x-wnba-stats-token": "true",
        'Accept-Encoding': 'gzip, deflate, br',
        'Accept-Language': 'en-US,en;q=0.9',
    }

    parameters = {
        'ContextMeasure': 'FGA',
        'LastNGames': 0,
        'LeagueID': '10',
        'Month': 0,
        'OpponentTeamID': 0,
        'Period': 0,
        'PlayerID': 100940,
        'SeasonType': 'Regular Season',
        'TeamID': 0,
        'VsDivision': '',
        'VsConference': '',
        'SeasonSegment': '',
        'Season': x,
        'RookieYear': '',
        'PlayerPosition': '',
        'Outcome': '',
        'Location': '',
        'GameSegment': '',
        'GameId': '',
        'DateTo': '',
        'DateFrom': ''
    }


    response = requests.get(url_base, params=parameters, headers=headers)
    content = json.loads(response.content)

    # transform contents into dataframe
    results = content['resultSets'][0]
    headers = results['headers']
    rows = results['rowSet']
    tempdf = pd.DataFrame(rows)
    tempdf.columns = headers

    # append to master dataframe
    df = df.append(tempdf)
        
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4899 entries, 0 to 376
Data columns (total 24 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   GRID_TYPE            4899 non-null   object
 1   GAME_ID              4899 non-null   object
 2   GAME_EVENT_ID        4899 non-null   int64
 3   PLAYER_ID            4899 non-null   int64
 4   PLAYER_NAME          4899 non-null   object
 5   TEAM_ID              4899 non-null   int64
 6   TEAM_NAME            4899 non-null   object
 7   PERIOD               4899 non-null   int64
 8   MINUTES_REMAINING    4899 non-null   int64
 9   SECONDS_REMAINING    4899 non-null   int64
 10  EVENT_TYPE           4899 non-null   object
 11  ACTION_TYPE          4899 non-null   object
 12  SHOT_TYPE            4899 non-null   object
 13  SHOT_ZONE_BASIC      4899 non-null   object
 14  SHOT_ZONE_AREA       4899 non-null   object
 15  SHOT_ZONE_RANGE      4899 non-null   object
 16  SHOT_DISTANCE        4899 non-null   int64
 17  LOC_X                4899 non-null   int64
 18  LOC_Y                4899 non-null   int64
 19  SHOT_ATTEMPTED_FLAG  4899 non-null   int64
 20  SHOT_MADE_FLAG       4899 non-null   int64
 21  GAME_DATE            4899 non-null   object
 22  HTM                  4899 non-null   object
 23  VTM                  4899 non-null   object
dtypes: int64(11), object(13)
memory usage: 956.8+ KB

#### 2016 - 2021 Regular Season

In [84]:
url_base = 'https://stats.wnba.com/stats/shotchartdetail'

# Regular season columns change for 2015 season so have to scrape in chunks and merge later. Same with playoffs.

for x in range(2016, 2022):
        
    headers = {
        'Host': 'stats.wnba.com',
        'Connection': 'keep-alive',
        'Accept': 'application/json, text/plain, */*',
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36',
        'Referer': 'https://stats.wnba.com/',
        "x-wnba-stats-origin": "stats",
        "x-wnba-stats-token": "true",
        'Accept-Encoding': 'gzip, deflate, br',
        'Accept-Language': 'en-US,en;q=0.9',
    }

    parameters = {
        'ContextMeasure': 'FGA',
        'LastNGames': 0,
        'LeagueID': '10',
        'Month': 0,
        'OpponentTeamID': 0,
        'Period': 0,
        'PlayerID': 100940,
        'SeasonType': 'Regular Season',
        'TeamID': 0,
        'VsDivision': '',
        'VsConference': '',
        'SeasonSegment': '',
        'Season': x,
        'RookieYear': '',
        'PlayerPosition': '',
        'Outcome': '',
        'Location': '',
        'GameSegment': '',
        'GameId': '',
        'DateTo': '',
        'DateFrom': ''
    }


    response = requests.get(url_base, params=parameters, headers=headers)
    content = json.loads(response.content)

    # transform contents into dataframe
    results = content['resultSets'][0]
    headers = results['headers']
    rows = results['rowSet']
    tempdf = pd.DataFrame(rows)
    tempdf.columns = headers

    # append to master dataframe
    df = df.append(tempdf)
        
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6693 entries, 0 to 191
Data columns (total 24 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   GRID_TYPE            6693 non-null   object
 1   GAME_ID              6693 non-null   object
 2   GAME_EVENT_ID        6693 non-null   int64
 3   PLAYER_ID            6693 non-null   int64
 4   PLAYER_NAME          6693 non-null   object
 5   TEAM_ID              6693 non-null   int64
 6   TEAM_NAME            6693 non-null   object
 7   PERIOD               6693 non-null   int64
 8   MINUTES_REMAINING    6693 non-null   int64
 9   SECONDS_REMAINING    6693 non-null   int64
 10  EVENT_TYPE           6693 non-null   object
 11  ACTION_TYPE          6693 non-null   object
 12  SHOT_TYPE            6693 non-null   object
 13  SHOT_ZONE_BASIC      6693 non-null   object
 14  SHOT_ZONE_AREA       6693 non-null   object
 15  SHOT_ZONE_RANGE      6693 non-null   object
 16  SHOT_DISTANCE        6693 non-null   int64
 17  LOC_X                6693 non-null   int64
 18  LOC_Y                6693 non-null   int64
 19  SHOT_ATTEMPTED_FLAG  6693 non-null   int64
 20  SHOT_MADE_FLAG       6693 non-null   int64
 21  GAME_DATE            6693 non-null   object
 22  HTM                  6693 non-null   object
 23  VTM                  6693 non-null   object
dtypes: int64(11), object(13)
memory usage: 1.3+ MB

#### Playoffs

In [85]:
url_base = 'https://stats.wnba.com/stats/shotchartdetail'

# DT was out most of 2019 season and missed playoffs
 
for x in [2007, 2009, 2010, 2011, 2013, 2014, 2016, 2017, 2018, 2020, 2021]: 
    headers = {
        'Host': 'stats.wnba.com',
        'Connection': 'keep-alive',
        'Accept': 'application/json, text/plain, */*',
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36',
        'Referer': 'https://stats.wnba.com/',
        "x-wnba-stats-origin": "stats",
        "x-wnba-stats-token": "true",
        'Accept-Encoding': 'gzip, deflate, br',
        'Accept-Language': 'en-US,en;q=0.9',
    }

    parameters = {
        'ContextMeasure': 'FGA',
        'LastNGames': 0,
        'LeagueID': '10',
        'Month': 0,
        'OpponentTeamID': 0,
        'Period': 0,
        'PlayerID': 100940,
        'SeasonType': 'Playoffs',
        'TeamID': 0,
        'VsDivision': '',
        'VsConference': '',
        'SeasonSegment': '',
        'Season': x,
        'RookieYear': '',
        'PlayerPosition': '',
        'Outcome': '',
        'Location': '',
        'GameSegment': '',
        'GameId': '',
        'DateTo': '',
        'DateFrom': ''
    }


    response = requests.get(url_base, params=parameters, headers=headers)
    content = json.loads(response.content)

    # transform contents into dataframe
    results = content['resultSets'][0]
    headers = results['headers']
    rows = results['rowSet']
    tempdf = pd.DataFrame(rows)
    tempdf.columns = headers

    # append to master dataframe
    df = df.append(tempdf)

df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7764 entries, 0 to 132
Data columns (total 24 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   GRID_TYPE            7764 non-null   object
 1   GAME_ID              7764 non-null   object
 2   GAME_EVENT_ID        7764 non-null   int64
 3   PLAYER_ID            7764 non-null   int64
 4   PLAYER_NAME          7764 non-null   object
 5   TEAM_ID              7764 non-null   int64
 6   TEAM_NAME            7764 non-null   object
 7   PERIOD               7764 non-null   int64
 8   MINUTES_REMAINING    7764 non-null   int64
 9   SECONDS_REMAINING    7764 non-null   int64
 10  EVENT_TYPE           7764 non-null   object
 11  ACTION_TYPE          7764 non-null   object
 12  SHOT_TYPE            7764 non-null   object
 13  SHOT_ZONE_BASIC      7764 non-null   object
 14  SHOT_ZONE_AREA       7764 non-null   object
 15  SHOT_ZONE_RANGE      7764 non-null   object
 16  SHOT_DISTANCE        7764 non-null   int64
 17  LOC_X                7764 non-null   int64
 18  LOC_Y                7764 non-null   int64
 19  SHOT_ATTEMPTED_FLAG  7764 non-null   int64
 20  SHOT_MADE_FLAG       7764 non-null   int64
 21  GAME_DATE            7764 non-null   object
 22  HTM                  7764 non-null   object
 23  VTM                  7764 non-null   object
dtypes: int64(11), object(13)
memory usage: 1.5+ MB

In [86]:
df.head()

,GRID_TYPE,GAME_ID,GAME_EVENT_ID,PLAYER_ID,PLAYER_NAME,TEAM_ID,TEAM_NAME,PERIOD,MINUTES_REMAINING,SECONDS_REMAINING,...,SHOT_ZONE_AREA,SHOT_ZONE_RANGE,SHOT_DISTANCE,LOC_X,LOC_Y,SHOT_ATTEMPTED_FLAG,SHOT_MADE_FLAG,GAME_DATE,HTM,VTM
0,Shot Chart Detail,1020400002,28,100940,Diana Taurasi,1611661317,Phoenix Mercury,1,16,36,...,Left Side Center(LC),16-24 ft.,21,-123,179,1,1,20040520,PHO,SAC
1,Shot Chart Detail,1020400002,62,100940,Diana Taurasi,1611661317,Phoenix Mercury,1,12,42,...,Left Side(L),16-24 ft.,21,-179,120,1,0,20040520,PHO,SAC
2,Shot Chart Detail,1020400002,71,100940,Diana Taurasi,1611661317,Phoenix Mercury,1,11,57,...,Left Side(L),8-16 ft.,10,-90,59,1,0,20040520,PHO,SAC
3,Shot Chart Detail,1020400002,93,100940,Diana Taurasi,1611661317,Phoenix Mercury,1,9,17,...,Left Side(L),16-24 ft.,18,-161,91,1,0,20040520,PHO,SAC
4,Shot Chart Detail,1020400002,96,100940,Diana Taurasi,1611661317,Phoenix Mercury,1,8,39,...,Left Side Center(LC),16-24 ft.,22,-172,138,1,1,20040520,PHO,SAC

In [87]:
# Pickle dataframe to use later
df.to_pickle('shot_data.pkl')

#### Basketball Reference game stats

In [88]:
# Read in team stats spreadsheet
filename = 'wnba_team_stats/{}-Table 1.csv'
df_list = []
team_list = ['MIN', 'NYL', 'TUL', 'LAS', 'SEA', 'CHI', 'SAS', 'WAS', 'ATL', 'IND', 'CON', 'CHA', 'SAC', 'HOU']

for team in team_list:
    df_list.append(pd.read_csv(filename.format(team)))

teams_df = pd.concat(df_list)

In [89]:
teams_df.columns

Index(['Season', 'Team', 'W', 'L', 'Rank', 'Unnamed: 5', 'G', 'MP', 'FG',
       'FGA', 'FG%', '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'FT', 'FTA',
       'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS'],
      dtype='object')

In [90]:
teams_df.drop(columns='Unnamed: 5', inplace=True)

In [91]:
teams_df.columns

Index(['Season', 'Team', 'W', 'L', 'Rank', 'G', 'MP', 'FG', 'FGA', 'FG%', '3P',
       '3PA', '3P%', '2P', '2PA', '2P%', 'FT', 'FTA', 'FT%', 'ORB', 'DRB',
       'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS'],
      dtype='object')

In [92]:
# Pickle df for later
teams_df.to_pickle('teams_data.pkl')